[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
solc = "0.8.18"

[rpc_endpoints]
ethereum="https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
localhost="http://localhost:8545"
goerli="https://goerli.infura.io/v3/${INFURA_API_KEY}"
cronos="https://evm.cronos.org/"
cronos_testnet="https://evm-t3.cronos.org/"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config